CREATE DATABASE things_records;

CREATE TABLE item (
  id INT GENERATED ALWAYS AS IDENTITY,
  publish_date DATE,
  archived BOOLEAN,
  genre VARCHAR(50),
  PRIMARY KEY(id)
);

-- Member 1 Work

CREATE TABLE LABEL(
    ID INT CONSTRAINT ID_LABEL_PK PRIMARY KEY,
    TITLE VARCHAR,
    COLOR VARCHAR
);

CREATE TABLE BOOKS(
    ID INT CONSTRAINT ID_BOOKS_PK PRIMARY KEY,
    PUBLISHER VARCHAR,
    COVER_STATE VARCHAR,
    PUBLISH_DATE DATE,
    ARCHIVED BOOLEAN,
    LABEL_ID COSTRAINT LABEL-ID_BOOKS_FK REFERENCES LABEL(ID) 
);

-- Member 2 Work
CREATE TABLE genre (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(50)
);

CREATE TABLE music_album (
  id INT GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(100),
  on_spotify BOOLEAN,
  PRIMARY KEY(id),
  CONSTRAINT FK_albumId FOREIGN KEY(id) REFERENCES item(id)
);
-- Member 3 Work

CREATE TABLE Author(
    id INT CONSTRAINT ID_Author_PK PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50)
);

CREATE TABLE Games(
    id INT CONSTRAINT ID_Games_PK PRIMARY KEY,
    multiplayer VARCHAR(50),
    last_played_at DATE,
    publish_date DATE,
    archived BOOLEAN,
    author_id COSTRAINT author-id_FK REFERENCES Author(ID) 
);