CREATE TABLE LABEL(
    ID INT CONSTRAINT ID_LABEL_PK PRIMARY KEY,
    TITLE VARCHAR,
    COLOR VARCHAR
);

CREATE TABLE BOOKS(
    ID INT CONSTRAINT ID_BOOKS_PK PRIMARY KEY,
    PUBLISHER VARCHAR,
    COVER_STATE VARCHAR,
    PUBLISH_DATE DATE,
    ARCHIVED BOOLEAN,
    LABEL_ID COSTRAINT LABEL-ID_BOOKS_FK REFERENCES LABEL(ID) 
);