CREATE DATABASE things_records;

-- Member 1 Work

CREATE TABLE LABEL(
    ID INT CONSTRAINT ID_LABEL_PK PRIMARY KEY,
    TITLE VARCHAR,
    COLOR VARCHAR
);

CREATE TABLE BOOKS(
    ID INT CONSTRAINT ID_BOOKS_PK PRIMARY KEY,
    PUBLISHER VARCHAR,
    COVER_STATE VARCHAR,
    PUBLISH_DATE DATE,
    ARCHIVED BOOLEAN,
    LABEL_ID COSTRAINT LABEL-ID_BOOKS_FK REFERENCES LABEL(ID) 
);

-- Member 2 Work
CREATE TABLE GENRE (
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NAME VARCHAR(50)
);

CREATE TABLE music_album (
  ID INT GENERATED ALWAYS AS IDENTITY,
  NAME VARCHAR(100),
  ON_SPOTIFY BOOLEAN,
  PRIMARY KEY(id),
  CONSTRAINT FK_albumId FOREIGN KEY(ID) REFERENCES item(ID)
);
-- Member 3 Work

CREATE TABLE Author(
    ID INT CONSTRAINT ID_Author_PK PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);

CREATE TABLE Games(
    ID INT CONSTRAINT ID_Games_PK PRIMARY KEY,
    MULTIPLAYER VARCHAR(50),
    LAST_PLAYED_AT DATE,
    PUBLISH_DATE DATE,
    ARCHIVED BOOLEAN,
    AUTHOR_ID COSTRAINT author-id_FK REFERENCES Author(ID) 
);